### ISSUE TITLE
Use libjpeg-turbo instead of jpeglib

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [evil-inject0r/Source-Engine-2019#16]
From **libjpeg-turbo Page**

> libjpeg-turbo is a JPEG image codec that uses SIMD instructions (MMX, SSE2, AVX2, NEON, AltiVec) to accelerate baseline JPEG compression and decompression on x86, x86-64, ARM, and PowerPC systems, as well as progressive JPEG compression on x86 and x86-64 systems. On such systems, libjpeg-turbo is generally 2-6x as fast as libjpeg, all else being equal. On other types of systems, libjpeg-turbo can still outperform libjpeg by a significant amount, by virtue of its highly-optimized Huffman coding routines. In many cases, the performance of libjpeg-turbo rivals that of proprietary high-speed JPEG codecs.
> 
> libjpeg-turbo implements both the traditional libjpeg API as well as the less powerful but more straightforward TurboJPEG API. libjpeg-turbo also features colorspace extensions that allow it to compress from/decompress to 32-bit and big-endian pixel buffers (RGBX, XBGR, etc.), as well as a full-featured Java interface.

Link: [https://libjpeg-turbo.org/](libjpeg-turbo)

**Comment by evil-inject0r** [comment]
there would be very little gained here. source only uses libjpeg for converting jpegs to tgas when importing sprays. in the engine for taking screenshots.

thanks for the suggestion it will be kept in mind.
