### ISSUE TITLE
include shader generation in the azure build system

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [evil-inject0r/Source-Engine-2019#25]
like the title say, if the shaders are include in the build pipeline it makes easy to generathe the shaders combos that are need for stdshader

**Comment by evil-inject0r** [comment]
this is something i am looking into. right now shader compiling relies on perl which is not available in the build pipeline.

**Comment by evil-inject0r** [comment]
i have included prebuilt shaders as a git submodule. this will save build minutes and it will be easier to build the project for new people.
