### ISSUE TITLE
shaders fails to compile

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [evil-inject0r/Source-Engine-2019#26]
like the title says the shadercompile refuses to genenrate the combos and the shadercompiler is not looking for dx_proxy (maybe is related to the Directx dependensies being in thirdparty folder)

**Comment by evil-inject0r** [comment]
whwn was the last time you tried? i compiled it yesterday

**Comment by FriskTheFallenHuman** [comment]
@evil-inject0r  yesterday

**Comment by evil-inject0r** [comment]
this should be fixed. can you tell me a bit more about what is happening?

**Comment by FriskTheFallenHuman** [comment]
well the problem begins when i launch the **_buildallshaders**. everything fine until it try to find dx_proxy,  so i just modify the .bat to point to the new location of the dll in thirdparty folder and well that's i only change the .bat

**Comment by evil-inject0r** [comment]
you were right. it turns out i was using old dlls. i hvae fixed the problem in the latest commit

thanks for finding this!
